# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
name: markdownlint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  markdownlint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: articulate/actions-markdownlint@v1
