# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
name: maven
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  maven:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Verify
        run: mvn verify -Pqulice --batch-mode
